# Generated by Django 2.2.4 on 2020-01-09 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='cctv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='closing_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='fast_dc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='no_of_ports',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='opening_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='restroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='slow_ac',
            field=models.IntegerField(default=0),
        ),
    ]
