# Generated by Django 2.2 on 2020-03-07 09:56

from django.db import migrations, models
import django.db.models.deletion
import userapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=userapp.models.duration)),
                ('elec_consumption', models.IntegerField(default=userapp.models.cost)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordof', to='userapp.Consumer')),
                ('cs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.ChargingStation')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csvehicles', to='userapp.Vehicle')),
            ],
        ),
    ]
