# Generated by Django 2.2 on 2020-03-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0002_csreport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="csreport",
            name="t24",
        ),
    ]
