# Generated by Django 2.2.4 on 2020-01-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20200109_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='stations_pics'),
        ),
    ]
