# Generated by Django 2.2 on 2020-03-08 12:01

from django.db import migrations, models
import django.db.models.deletion
import userapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0003_remove_csreport_t24"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChargingStationWeekly",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("d1", models.IntegerField(default=userapp.models.cost)),
                ("d2", models.IntegerField(default=userapp.models.cost)),
                ("d3", models.IntegerField(default=userapp.models.cost)),
                ("d4", models.IntegerField(default=userapp.models.cost)),
                ("d5", models.IntegerField(default=userapp.models.cost)),
                ("d6", models.IntegerField(default=userapp.models.cost)),
                ("d7", models.IntegerField(default=userapp.models.cost)),
                (
                    "cs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userapp.ChargingStation",
                    ),
                ),
            ],
        ),
    ]
