# Generated by Django 2.2.4 on 2020-01-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_chargingstation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='price_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
