# Generated by Django 2.2.4 on 2020-01-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_chargingstation_price_kwh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='station_pics'),
        ),
    ]
