# Generated by Django 3.0.2 on 2020-01-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_auto_20200109_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='closing_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='opening_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
