# Generated by Django 3.0.5 on 2020-04-14 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_csmaintenance_maintenancemandetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancemandetails',
            name='own',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='userapp.Provider'),
            preserve_default=False,
        ),
    ]
