# Generated by Django 3.0.2 on 2020-01-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20200110_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='image',
            field=models.ImageField(null=True, upload_to='station_pics'),
        ),
    ]
