# Generated by Django 3.0.5 on 2020-04-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_maintenancemandetails_own'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancemandetails',
            name='City',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
