# Generated by Django 3.0.2 on 2020-01-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_auto_20200110_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='suburb',
            field=models.CharField(default='', max_length=100),
        ),
    ]
