# Generated by Django 3.0.5 on 2020-04-16 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_maintenancemandetails_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csmaintenance',
            name='csm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='userapp.Provider'),
        ),
    ]
