# Generated by Django 3.0.2 on 2020-01-11 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_auto_20200111_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
