# Generated by Django 3.0.2 on 2020-01-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_chargingstation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='image',
            field=models.ImageField(blank=True, upload_to='provider_pics'),
        ),
    ]
