# Generated by Django 3.0.5 on 2020-04-16 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0009_auto_20200416_1032"),
    ]

    operations = [
        migrations.AddField(
            model_name="csmaintenance",
            name="CsSelect",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="userapp.ChargingStation",
            ),
            preserve_default=False,
        ),
    ]
