# Generated by Django 3.0.2 on 2020-01-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_provider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='available_ports',
            field=models.IntegerField(default=0),
        ),
    ]
