# Generated by Django 2.2 on 2020-03-05 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_chargingstation_available_ports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='image',
            field=models.ImageField(default='station_pics/default.jpg', null=True, upload_to='station_pics'),
        ),
        migrations.CreateModel(
            name='ChargingStationRecord',
            fields=[
                ('cs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='userapp.ChargingStation')),
                ('starttime', models.TimeField(default='00:00:00')),
                ('stoptime', models.TimeField(default='00:00:00')),
                ('elec_kwh', models.DecimalField(decimal_places=6, max_digits=9)),
                ('vehicle', models.ManyToManyField(related_name='csvehicles', to='userapp.Vehicle')),
            ],
        ),
    ]
