# Generated by Django 2.2 on 2020-03-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_auto_20200305_1244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChargingStationRecord',
        ),
    ]
