# Generated by Django 2.2 on 2020-03-06 02:21

from django.db import migrations, models
import django.db.models.deletion
import userapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_chargingstationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsReport',
            fields=[
                ('cs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='userapp.ChargingStation')),
                ('time', models.DateField(default=userapp.models.randomdate)),
                ('t0', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t1', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t2', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t3', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t4', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t5', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t6', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t7', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t8', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t9', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t10', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t11', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t12', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t13', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t14', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t15', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t16', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t17', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t18', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t19', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t20', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t21', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t22', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t23', models.IntegerField(default=userapp.models.randomvehicles)),
                ('t24', models.IntegerField(default=userapp.models.randomvehicles)),
            ],
        ),
    ]
