# Generated by Django 2.2 on 2020-03-06 02:29

from django.db import migrations, models
import userapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_csreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstationrecord',
            name='elec_kwh',
            field=models.DecimalField(decimal_places=6, default=userapp.models.cost, max_digits=9),
        ),
    ]
