# Generated by Django 2.2 on 2020-03-06 02:40

from django.db import migrations, models
import userapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_auto_20200306_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='city',
            field=models.CharField(default=userapp.models.geocity, max_length=100),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='name',
            field=models.CharField(default=userapp.models.csnames, max_length=100),
        ),
    ]
