# Generated by Django 3.0.5 on 2020-05-19 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0015_auto_20200508_0959"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("stop_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "lat",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
                ),
                (
                    "lng",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles_charged",
                        to="userapp.Vehicle",
                    ),
                ),
            ],
        ),
    ]
