# Generated by Django 2.2 on 2020-03-06 02:43

from django.db import migrations, models
import userapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_auto_20200306_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='suburb',
            field=models.CharField(default=userapp.models.geosub, max_length=100),
        ),
    ]
