# Generated by Django 2.2 on 2020-03-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_auto_20200306_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type4or2',
            field=models.IntegerField(),
        ),
    ]
