# Generated by Django 3.0.5 on 2020-05-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_userrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='port_type',
            field=models.CharField(choices=[('Type1', 'Type1'), ('Type2', 'Type2'), ('Type3', 'Type3')], default='', max_length=20),
        ),
    ]
