# Generated by Django 2.2 on 2020-03-06 03:02

from django.db import migrations, models
import userapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_auto_20200306_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='cctv',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='fast_dc',
            field=models.IntegerField(default=userapp.models.fasports),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=18.483853, max_digits=9),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=73.841241, max_digits=9),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='no_of_ports',
            field=models.IntegerField(default=userapp.models.portscount),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='slow_ac',
            field=models.IntegerField(default=userapp.models.slowports),
        ),
    ]
