# Generated by Django 2.2 on 2020-03-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_auto_20200306_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=18.53052, max_digits=9),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=73.836474, max_digits=9),
        ),
    ]
