# Generated by Django 3.0.5 on 2020-06-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0021_vehicle_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="name",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
