# Generated by Django 3.0.5 on 2020-06-13 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0023_auto_20200613_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='vehicle_no',
        ),
        migrations.AddField(
            model_name='survey',
            name='vehicle_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userapp.Vehicle'),
            preserve_default=False,
        ),
    ]
