# Generated by Django 3.0.5 on 2020-07-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0024_auto_20200613_1250"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="price",
            new_name="ConsumptionPerMin",
        ),
    ]
