# Generated by Django 2.2 on 2020-03-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0024_auto_20200306_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargingstation',
            old_name='no_ports',
            new_name='no_of_ports',
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=18.5311, max_digits=9),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=73.867888, max_digits=9),
        ),
    ]
