# Generated by Django 3.0.5 on 2020-07-16 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0027_remove_vehicle_battery_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="ConsumptionPerMin",
            new_name="Charging_Rate",
        ),
    ]
