# Generated by Django 3.0.5 on 2020-07-24 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0028_auto_20200716_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstationrecord',
            name='cs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csrecord', to='userapp.ChargingStation'),
        ),
    ]
