# Generated by Django 2.2 on 2020-03-06 05:46

from django.db import migrations, models
import userapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0030_auto_20200306_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='closing_time',
            field=models.TimeField(default=userapp.models.stoptime),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=18.517852, max_digits=9),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=73.836394, max_digits=9),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='opening_time',
            field=models.TimeField(default=userapp.models.starttime),
        ),
    ]
