# Generated by Django 2.2 on 2020-03-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0031_auto_20200306_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=18.51717, max_digits=9),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=73.813399, max_digits=9),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='price_kwh',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
