# Generated by Django 3.0.5 on 2020-08-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0034_covertspecs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covertspecs',
            name='Pricing',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='covertspecs',
            name='battery_capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='covertspecs',
            name='battery_warranty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='covertspecs',
            name='range_in_kms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='covertspecs',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
