# Generated by Django 3.0.5 on 2020-08-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0035_auto_20200802_1018"),
    ]

    operations = [
        migrations.AlterField(
            model_name="covertspecs",
            name="range_in_kms",
            field=models.CharField(max_length=20),
        ),
    ]
