# Generated by Django 3.0.5 on 2020-08-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0036_auto_20200802_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingEnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.IntegerField(default=0)),
                ('road_type', models.CharField(choices=[('City', 'City'), ('Highway', 'Highway'), ('Off road', 'Off road')], max_length=20)),
                ('consumption_per_100', models.IntegerField()),
                ('ac', models.BooleanField()),
                ('avg_speed', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user_convert_specs',
            name='price_range',
            field=models.CharField(choices=[('Below 5', 'Below 5'), ('5 to 7.5', '5 to 7.5'), ('above 7', 'above 7')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user_convert_specs',
            name='vehicle_type',
            field=models.CharField(choices=[('3 wheeler', '3 wheeler'), ('mini SUV', 'mini SUV'), ('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Heavy', 'Heavy')], default='', max_length=20),
        ),
    ]
