# Generated by Django 2.2 on 2020-03-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0039_auto_20200306_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='city',
            field=models.CharField(default='city', max_length=100),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='suburb',
            field=models.CharField(default='suburb', max_length=100),
        ),
    ]
